version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - 8082:80
        volumes:
            - ./source:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./source/storage/app/public:/usr/share/nginx/html/public/storage
            - ./source/storage/app/has_file:/usr/share/nginx/html/public/has_file
    php-fpm:
        build: ./php-fpm
        volumes:
            - ./source:/var/www/html
    mysqldb:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ft-system
            MYSQL_USER: sysuser
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql   
            - ./settings/sql:/var/lib/mysql/initdata
